### ISSUE TITLE
Other basline for the colosseum

### ISSUE THREAD

**Issue by Zed-Wu** [robot-colosseum/robot-colosseum#9]
Thank you for your great work! I notice that there are two 2D learning baselines (R3M-MLP, MVP-MLP) in the paper. Do you have any plan about releasing their codes? I want to do some work about the data augmentation, so I focus on the 2D image input.

Best regards

**Comment by wpumacay** [comment]
Hi @Zed-Wu , sorry for the delayed response. We have the code for RVT in [this](https://github.com/robot-colosseum/rvt_colosseum) repo, just in case. I don't think we'll be able to re-organize the code we have for the 2d baselines, as it's mixed with the implementation we used for PerAct. If you need to setup these 2d baselines, maybe I could help you integrate the code in the baselines original repository with Colosseum.

**Comment by Zed-Wu** [comment]
Hi，wpumacay,

Thank you for getting back to me. I appreciate the offer to help integrate the code. I will try it once I have time to do it

Best regards
